---
title: "HW 02"
author: "Cat Xia"
format: 
  html:
    embed-resources: true
toc: true
---

Install Packages
```{r install}
#| label: install
if (!require("pacman"))
  install.packages("pacman")

pacman::p_load(tidyverse, here, glue, scales, ggridges, dsbox) 
```


## 1 - A new day, a new plot, a new geom


```{r Q1 data cleaning and new columns}
#| label: Q1 data cleaning and new columns
edibnb <- edibnb |>
  group_by(neighbourhood) |>
  mutate(med_review = median(review_scores_rating, na.rm = TRUE)) |>
  ungroup() |>
  mutate(neighbourhood = fct_reorder(neighbourhood, med_review),
         #directed to documentation (https://forcats.tidyverse.org/reference/fct_reorder.html) through slack overflow
         
         neighbourhood = fct_explicit_na(neighbourhood, na_level = "Other/Unknown"))
        #attempted with replace_na() but unable to figure out why it didn't work. Consulted AI on why it didn't work and realized that neighbourhood was in the wrong class. Directed to fct_explicit_na and code written based off forcats documentation. (https://forcats.tidyverse.org/reference/fct_explicit_na.html)
  
edibnb
```
```{r}
edibnb |>
  ggplot(aes(x = review_scores_rating, y = neighbourhood)) +
  geom_density_ridges() +
  coord_cartesian(xlim = c(75, 105)) +
  theme_minimal()
```

## 2 - Foreign Connected PACs

```{r}
#| label: label-me-2

```

## 3 - Median housing prices in the US


## 4 - Expect More. Plot More.


## 5 - Mirror, mirror on the wall, who’s the ugliest of them all?
